version: '3.8'

services:
  advanced-stock-price-checker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: advanced-stock-price-checker
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
    restart: unless-stopped


